replicaCount: 1

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128M

image:
  repository: nginx   # Default repo
  isProduction: false # Flag for prod/dev

