apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- with .Values.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- with .Values.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: nginx
          image: {{ .Values.image.repository | default "library" | lower }}:{{ if .Values.image.isProduction }}1.27-alpine{{ else }}latest{{ end }}
          {{- include "myapp.containerResources" . | nindent 10 }}

